spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sakila
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
